### ISSUE TITLE
target_paths option in .travis.yml is ignored

### ISSUE THREAD

**Issue by mfornasa** [travis-ci/artifacts#47]
It seems that the option `--target-paths` is missing from `artifacts.go`.

**Comment by 0x6e6562** [comment]
Is this issue still current? I'm in the process of porting from the artifacts gem to the addon and I'm trying to specify a particular target path, but it seems that this is just getting ignored and there are no useable diagnostics to see where this might be going.

**Comment by meatballhat** [comment]
@0x6e6562 I believe this is "fixed" now in the `addons.artifacts` implementation via https://github.com/travis-ci/travis-build/commit/aa34739647430c6cb595b0f26921f63b9d7c7bd4.  Pretty please can you confirm?

**Comment by 0x6e6562** [comment]
@meatballhat Sorry for the radio silence :-(

I can confirm that this issue is now fixed on Travis CI, so thank you very much for patching this :-)

For anybody else reading this thread, here is the relevant part of my descriptor:

```
addons:
  artifacts:
    debug: true
    paths:
      - PATH_TO_MY_ARTIFACT
    target_paths: PATH_WITH_MY_S3_BUCKET/$TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: MY_S3_BUCKET
    s3_region: eu-west-1
```

Note that I am using the repository creds for this, as set using the travis gem:

```
$ travis env set AWS_SECRET_KEY fmAQd46zn2euqA827da3nb89c9 -r owner/repo
```

To check the creds for a repo:

```
$ travis env list -r owner/repo       
# environment variables for owner/repo
AWS_ACCESS_KEY=[secure]
AWS_SECRET_KEY=[secure]
```

**Comment by 0x6e6562** [comment]
Given that it works now, I would suggest that we close this issue now?

**Comment by meatballhat** [comment]
@0x6e6562 Thanks so much! :heart_eyes_cat:
