### ISSUE TITLE
ignores ARTIFACTS_KEY from repository settings

### ISSUE THREAD

**Issue by toolbear** [travis-ci/artifacts#56]
I think `artifacts upload` ignores env vars set in repository settings.

[Build #67](https://travis-ci.org/toolbear/panda/builds/50013497) fails:

``` console
Setting environment variables from repository settings
$ export ARTIFACTS_SECRET=[secure]
$ export ARTIFACTS_KEY=[secure]
...
$ artifacts upload
DEBUG: setting log level to debug
FATAL: no access key given
The command "artifacts upload" failed and exited with 1 during .
```

I can workaround this by setting them in `.travis.yml`. [Build #69](https://travis-ci.org/toolbear/panda/builds/50015365) succeeds:

``` console
Setting environment variables from repository settings
$ export ARTIFACTS_SECRET=[secure]
$ export ARTIFACTS_KEY=[secure]
...
Setting environment variables from .travis.yml
$ export ARTIFACTS_KEY=[secure]
$ export ARTIFACTS_SECRET=[secure]
...
$ artifacts upload
DEBUG: setting log level to debug
DEBUG: adding path
  path: &{/Users/travis/build/toolbear/panda hello }
DEBUG: adding path
  path: &{/Users/travis/build/toolbear/panda hola }
DEBUG: starting upload
```

Long term, I don't really want these credentials bound to the commit.

**Comment by meatballhat** [comment]
@toolbear Sorry about the big delay.  So far I've been unable to reproduce this bug, e.g.: https://travis-ci.org/meatballhat/cloaked-octo-tyrion/jobs/52970506.  I'm waiting to hear back about the OSX build: https://travis-ci.org/meatballhat/cloaked-octo-tyrion/jobs/52970509, wondering if there's some critical difference in the build env such that the `ARTIFACTS_*` vars are being unset...

**Comment by toolbear** [comment]
No worries. I'm not blocked. I stopped pursuing `travis-artifiacts` and `travis-deploy` when I discovered that both are intentionally disabled on pull requests.

**Comment by toolbear** [comment]
I wonder if you may have more success trying to reproduce with `language: objective-c` instead of `os: osx`?

**Comment by meatballhat** [comment]
@toolbear Gotcha.  The behavior wrt pull requests is a great point.  I'll ask around to see if this is something we should reconsider or at least make configurable.  As for `language: objective-c` vs `os: osx`, I'll give it a shot :smiley_cat:

**Comment by meatballhat** [comment]
@toolbear the plot thickens: https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/52994402  (:confused: :exclamation:)

**Comment by toolbear** [comment]
dramatic :shipit: 

Cursory look, the only difference I notice is  that I didn't provide an explicit `ARTIFACTS_BUCKET`…

If you don't mind leaving it open a while longer, I can try again later this week or over the weekend.

**Comment by meatballhat** [comment]
@toolbear friendly bump :smiley_cat:

**Comment by jMyles** [comment]
I too seem to be experiencing this issue.

**Comment by tystr** [comment]
I am also having this issue

**Comment by sjackman** [comment]
> No worries. I'm not blocked. I stopped pursuing travis-artifiacts and travis-deploy when I discovered that both are intentionally disabled on pull requests.

Support for pull requests would be a useful feature for me as well.

**Comment by sjackman** [comment]
@toolbear @meatballhat I've opened a feature request issue at Travis CI to implement artifact uploads for pull requests. https://github.com/travis-ci/travis-ci/issues/5579

**Comment by BanzaiMan** [comment]
Is this still an issue for push builds? https://travis-ci.org/BanzaiMan/homebrew-cask/builds/131510102 shows `$ARTIFACTS_KEY` is respected.

The use of secure variables in a PR is a separate issue which is discussed elsewhere.

**Comment by meatballhat** [comment]
afaict this bug has been addressed.  Please yell if you find otherwise!  :heart:
