### ISSUE TITLE
Only upload artifacts on a specific branch

### ISSUE THREAD

**Issue by margueritepd** [travis-ci/artifacts#70]
This issue I think pertains to code in https://github.com/travis-ci/travis-build but issues are disabled so I am coming here.

As far as I can tell from [source code](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/artifacts/validator.rb#L53) I should be able to specify a configuration that looks something like this:

```yaml
addons:
  artifacts:
    ...
    branch: master
```

and have artifacts only uploaded on the master branch. However I have been unable to get this to work, artifacts are uploaded on all branches (not on pull requests though). The docs say nothing WRT to filtering on branches.

**Comment by BanzaiMan** [comment]
Thanks for reporting the issue. I have identified the bug, and will work on a fix shortly.
