### ISSUE TITLE
Access Denied error not displayed on Travis

### ISSUE THREAD

**Issue by birdsarah** [travis-ci/artifacts#74]
My assets weren't uploading, this is the end of the debug output from Travis:

```sh
..
assets/style.css: no such file or directory
  retry: 2
ERROR: failed to upload: /home/travis/build/test/68998280.html
assets/20e28182428903b2619580fd00061422.txt
assets/2ab8a28e5882c593e79561e618a257a0.png
assets/49686bcc48c65a6fc1217fed3873dfdb.png
assets/d708b0fdf7ff39ed464c7d4542459263.txt
assets/style.css
  err: open /home/travis/build/test/68998280.html
assets/20e28182428903b2619580fd00061422.txt
assets/2ab8a28e5882c593e79561e618a257a0.png
assets/49686bcc48c65a6fc1217fed3873dfdb.png
assets/d708b0fdf7ff39ed464c7d4542459263.txt
assets/style.css: no such file or directory
Done uploading artifacts
```

When I ran locally with the same credentials, the result I got was

```sh
ERRO[0007] failed to upload: /tests/assets/style.css  err=Access Denied
ERRO[0007] failed to upload: /tests/123.html  err=Access Denied
```

So, I'm guessing I've got a permissions issue which is entirely possible. 

But it would have been helpful to see the `AccessDenied` error not `no such file or directory`

**Comment by BanzaiMan** [comment]
Sorry for the troubles. Could you open a new issue in https://github.com/travis-ci/travis-ci/issues? This issue looks like an invocation of `artifacts` in the context of Travis CI, rather than `artifacts` itself.

Thanks.

**Comment by birdsarah** [comment]
Thanks @BanzaiMan - https://github.com/travis-ci/travis-ci/issues/7501
