### ISSUE TITLE
Unsupported protocol scheme ""

### ISSUE THREAD

**Issue by kpp** [travis-ci/artifacts#77]
Hello!
I am trying to upload artifacts but I am getting this error:

```
ERROR: failed to upload: /home/travis/build/RnDome/test_travis_artifacts/build/test_project-0.1.0-Linux.zip

  err: Put /testtravisartifacts2/RnDome/test_travis_artifacts/19/19.1/build/test_project-0.1.0-Linux.zip: unsupported protocol scheme ""

Done uploading artifacts
```

See [this build](https://travis-ci.org/RnDome/test_travis_artifacts/builds/252396698)

List of failed regions:

Region | Error
------------ | -------------
eu-west-2 | unsupported protocol scheme ""
eu-central-1 | The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
ap-northeast-2 | unsupported protocol scheme ""

List of succeeded regions:

 * US East (N. Virginia)  - requires `export ARTIFACTS_REGION=""`

**Comment by BanzaiMan** [comment]
My guess is that the region `eu-west-2` is not supported.

**Comment by kpp** [comment]
Would you give me the list of supported regions?

**Comment by mzabaluev** [comment]
So, is it really "you can choose any AWS region as long as it is us-east-_n_"?

**Comment by ejhg** [comment]
I actually get `unsupported protocol scheme ""` for us-east-2.

So it seems that us-east-1 is the only supported region?

**Comment by ejhg** [comment]
For future reference, this seems to be a dup of https://github.com/travis-ci/artifacts/issues/57
